/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BubbleMenu: typeof import('./src/components/BubbleMenu.vue')['default']
    CommandsList: typeof import('./src/components/plugins/CommandsList.vue')['default']
    FixedMenu: typeof import('./src/components/FixedMenu.vue')['default']
    FloatingMenu: typeof import('./src/components/FloatingMenu.vue')['default']
  }
}
